apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: tpint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
      - name: traefik
        image: traefik:v3.0.1
        args:
        - --configFile=/etc/traefik/traefik.yml
        ports:
        - name: web
          containerPort: 80
        - name: websecure
          containerPort: 443
        - name: dashboard
          containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/traefik
          readOnly: true
        - name: acme
          mountPath: /acme.json
          readOnly: false
      volumes:
      - name: config
        configMap:
          name: traefik-config
      - name: acme
        emptyDir: {}
