- name: Configurar servidores web y base de datos
  hosts: webservers
  become: true
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Habilitar Apache al inicio
      service:
        name: apache2
        state: started
        enabled: true

    - name: Cambiar contenido del archivo HTML
      copy:
        content: "<h1>Hola Devops!!!</h1>"
        dest: /var/www/html/index.html

- name: Configurar servidor de base de datos
  hosts: databases
  become: true
  tasks:
    - name: Instalar MySQL
      apt:
        name: mysql-server
        state: present

    - name: Instalar PyMySQL
      apt:
        name: python3-pymysql
        state: present

    - name: Crear archivo .my.cnf
      copy:
        content: |
          [client]
          user=root
          password=secret
        dest: /root/.my.cnf
        mode: '0600'

    - name: Crear nuevo usuario con permisos administrativos
      mysql_user:
        name: admin
        password: admin
        priv: '*.*:ALL,GRANT'
        host: "%"
        state: present
        login_user: root
        login_password: secret
        login_host: localhost
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Configurar MySQL para aceptar conexiones remotas
      shell: |
        sed -i 's/^\(bind-address\s*=\s*\).*$/\1 0.0.0.0/' /etc/mysql/mysql.conf.d/mysqld.cnf
        systemctl restart mysql

    - name: Crear base de datos y usuario
      mysql_db:
        name: mydatabase
        state: present

    - name: Crear usuario de MySQL
      mysql_user:
        name: myuser
        password: mypassword
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: Reiniciar MySQL
      service:
        name: mysql
        state: restarted
        enabled: true
