- name: Instalar servidor web y cambiar contenido HTML
  hosts: all
  become: true
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
    - name: Habilitar Apache al inicio
      service:
        name: apache2
        state: started
        enabled: true
    - name: Cambiar contenido del archivo HTML
      copy:
        content: "<h1>Hola Devops!!!</h1>"
        dest: /var/www/html/index.html             

