apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: tpint
data:
  traefik.yml: |
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    api:
      dashboard: true
      insecure: true
    entryPoints:
      web:
        address: ":80"
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        address: ":443"
    certificatesResolvers:
      myresolver:
        acme:
          email: romanfandrich@gmail.com
          storage: acme.json
          httpChallenge:
            entryPoint: web
    providers:
      docker:
        exposedByDefault: false
